### ISSUE TITLE
OVDK through-put performance related to lcore-- port--queue mapping

### ISSUE THREAD

**Issue by Ksamasi** [01org/dpdk-ovs#55]
Hi Team ,
I am using OVDK-1.2 am trying find out how to map lcore -- >vports -- > queuesin code level for increase through-put .
Suggestions are welcome on this .
 
I was trying to send 6 Gbps input to switch but output is 4.6 Gbps (64 byte packets ).

I think lcores are connected to vport , and vports are connected to physical queues .

**Comment by ovsdpdk** [comment]
Hello I am following the installation guide and facing an issue i.e

configuring and make dpdk (ver 1.7.1) gives no error
when i configure ovs_dpdk (verision taken from https://github.com/01org/dpdk-ovs/ ) i.e
./configure RTE_SDK=/home/.../ovs_dpdk/DPDK --disable-ssl
-> no error comes
but when i make it, following error comes

lib/.libs/libopenvswitch.a(dpdk-link.o): In function ring_lookup': /home/...../ovs_dpdk/ovdk/openvswitch/lib/dpdk-link.c:384: undefined reference torte_ring_lookup'
collect2: ld returned 1 exit status

Plz help me !!!!!

**Comment by indexOutOfBound5** [comment]
Please see the following post on the mailing list:
https://lists.01.org/pipermail/dpdk-ovs/2015-February/002166.html

And the following thread on the mailing list:
https://lists.01.org/pipermail/dpdk-ovs/2015-February/002156.html

Marking this issue as closed as it has been discussed on the mailing list.
