### ISSUE TITLE
Compiling error of ovs_dpdk on Ubuntu 12.04

### ISSUE THREAD

**Issue by ovsdpdk** [01org/dpdk-ovs#56]
configuring and make dpdk (ver 1.7.1) gives no error
when i configure ovs_dpdk (verision taken from https://github.com/01org/dpdk-ovs/ )  i.e
./configure RTE_SDK=/home/.../ovs_dpdk/DPDK --disable-ssl
-> no error comes
but when i make it, following error comes

lib/.libs/libopenvswitch.a(dpdk-link.o): In function `ring_lookup':
/home/...../ovs_dpdk/ovdk/openvswitch/lib/dpdk-link.c:384: undefined reference to `rte_ring_lookup'
collect2: ld returned 1 exit status

Plz help me !!!!!

**Comment by indexOutOfBound5** [comment]
The following patch from the mailing list should resolve your issue:
https://lists.01.org/pipermail/dpdk-ovs/2015-February/002137.html

Thanks,
Meghan

**Comment by ovsdpdk** [comment]
Could you please tell me little bit more, I could not able to properly understand the patch link you have given. I am tryng to install openvswitch in Ubuntu ver 12.04 with Dpdk 1.7.1 and openvswitch of release 1.2. Since Patch says : 
The problem is solved by passing -lintel_dpdk in LDADD and -Llibdir
in LDFLAGS to libtool instead of giving the absolute path of
libintel_dpdk.so to libtool.
How could i actually do this !!!

**Comment by indexOutOfBound5** [comment]
The second answer to this question does a pretty good job of explaining what a patch is:
http://stackoverflow.com/questions/8279602/what-is-a-patch-in-git-version-control

And here's a description of how to apply a patch (you can ignore the section on creating the patch):
https://ariejan.net/2009/10/26/how-to-create-and-apply-a-patch-with-git/

Unless you have a mail program like mutt running locally on your machine, I'd copy paste the entire text of that mail into a new text file, and use that to complete the steps in the tutorial above.

What you are quoting there is the commit message included with the patch, not the patch itself. If you have problems after applying the patch, the replies to the patch thread should have more information.

Thanks,
Meghan

**Comment by ovsdpdk** [comment]
Ok thanks for ur Guidance !!

**Comment by ovsdpdk** [comment]
Dear Meghan could you please tell me while applying patch, the file.c which need to be changed with patch.c file, from where and how could i get this patch.c or according to you exactly which text portion should i copy like if i want to apply the following patch http://patchwork.openvswitch.org/patch/6617/
Thanks in advance !!
