### ISSUE TITLE
OVS has built-in DPDK support now, please follow your nose to OVS

### ISSUE THREAD

**Issue by steevenlee** [01org/dpdk-ovs#62]
This code base only support DPDK 1.7, please visit OVS to support latest DPDK:
https://github.com/openvswitch/ovs/blob/master/INSTALL.DPDK.md

**Comment by tbarbette** [comment]
Why is this repo still open and/or the main README not updated then  ?

**Comment by mrmarkgray** [comment]
I updated the README.
