### ISSUE TITLE
bridge creation

### ISSUE THREAD

**Issue by Barathi07** [01org/dpdk-ovs#63]
Pls tell me which part of code handles the following part:
**ovs-vsctl set bridge s1 datapath_type=netdev**

I need to set bridge and set datapath_type as netdev in my own script.
[OVS_GITHUB.txt](https://github.com/01org/dpdk-ovs/files/156527/OVS_GITHUB.txt)

With this code am able to create bridge. But, when i issue, **ovs-ofctl dump-flows s1** .
Am getting the foll error:
ovs-ofctl: s1 is not a bridge or a socket
Pls suggest a solution.

**Comment by mrmarkgray** [comment]
Hi,

Wrong list. You need to post this to dev@openvswitch.org.

Mark
